/* 
 * tradin.api.server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using template.api.httpclient.Api;
using template.api.httpclient.Model;
using template.api.httpclient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace template.api.httpclient.Test
{
    /// <summary>
    ///  Class for testing PackageJson
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PackageJsonTests
    {
        // TODO uncomment below to declare an instance variable for PackageJson
        //private PackageJson instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PackageJson
            //instance = new PackageJson();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PackageJson
        /// </summary>
        [Test]
        public void PackageJsonInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PackageJson
            //Assert.IsInstanceOf(typeof(PackageJson), instance);
        }


        /// <summary>
        /// Test the property 'name'
        /// </summary>
        [Test]
        public void nameTest()
        {
            // TODO unit test for the property 'name'
        }
        /// <summary>
        /// Test the property 'version'
        /// </summary>
        [Test]
        public void versionTest()
        {
            // TODO unit test for the property 'version'
        }
        /// <summary>
        /// Test the property 'description'
        /// </summary>
        [Test]
        public void descriptionTest()
        {
            // TODO unit test for the property 'description'
        }
        /// <summary>
        /// Test the property 'author'
        /// </summary>
        [Test]
        public void authorTest()
        {
            // TODO unit test for the property 'author'
        }

    }

}
