/* 
 * tradin.api.server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = template.api.httpclient.Client.OpenAPIDateConverter;

namespace template.api.httpclient.Model
{
    /// <summary>
    /// PackageJson
    /// </summary>
    [DataContract]
    public partial class PackageJson :  IEquatable<PackageJson>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PackageJson" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="version">version.</param>
        /// <param name="description">description.</param>
        /// <param name="author">author.</param>
        public PackageJson(string name = default(string), string version = default(string), string description = default(string), string author = default(string))
        {
            this.name = name;
            this.version = version;
            this.description = description;
            this.author = author;
        }
        
        /// <summary>
        /// Gets or Sets name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string name { get; set; }

        /// <summary>
        /// Gets or Sets version
        /// </summary>
        [DataMember(Name="version", EmitDefaultValue=false)]
        public string version { get; set; }

        /// <summary>
        /// Gets or Sets description
        /// </summary>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string description { get; set; }

        /// <summary>
        /// Gets or Sets author
        /// </summary>
        [DataMember(Name="author", EmitDefaultValue=false)]
        public string author { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PackageJson {\n");
            sb.Append("  name: ").Append(name).Append("\n");
            sb.Append("  version: ").Append(version).Append("\n");
            sb.Append("  description: ").Append(description).Append("\n");
            sb.Append("  author: ").Append(author).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PackageJson);
        }

        /// <summary>
        /// Returns true if PackageJson instances are equal
        /// </summary>
        /// <param name="input">Instance of PackageJson to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PackageJson input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.name == input.name ||
                    (this.name != null &&
                    this.name.Equals(input.name))
                ) && 
                (
                    this.version == input.version ||
                    (this.version != null &&
                    this.version.Equals(input.version))
                ) && 
                (
                    this.description == input.description ||
                    (this.description != null &&
                    this.description.Equals(input.description))
                ) && 
                (
                    this.author == input.author ||
                    (this.author != null &&
                    this.author.Equals(input.author))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.name != null)
                    hashCode = hashCode * 59 + this.name.GetHashCode();
                if (this.version != null)
                    hashCode = hashCode * 59 + this.version.GetHashCode();
                if (this.description != null)
                    hashCode = hashCode * 59 + this.description.GetHashCode();
                if (this.author != null)
                    hashCode = hashCode * 59 + this.author.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
